apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JacobVHS/argo-demo
    targetRevision: HEAD
    path: my-bluegreen-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
